name: PyQUDA-Utils publish

on:
  workflow_dispatch:

jobs:
  pypi-publish:

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/PyQUDA-Utils

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: python -m pip install build

      - name: Build sdist
        run: python -m build . --sdist

      - name: Publish sdist
        uses: pypa/gh-action-pypi-publish@release/v1
