name: Python package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Which tag to create and release?
        required: true
        default: 0.0.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel Cython

      - name: Build sdist
        run: python setup.py sdist

      - name: Upload sdist
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.tag }}
          files: dist/PyQUDA-${{ github.event.inputs.tag }}.tar.gz
          fail_on_unmatched_files: true
